### ISSUE TITLE
Import WireGuard Via New Patcher, Not Directly in Tree

### ISSUE THREAD

**Issue by zx2c4** [msdx321/android_kernel_google_wahoo#1]
Some recent WireGuard changes I thought I should tell you about here.

You've been building WireGuard as part of this kernel by actually committing the WireGuard source code. *Please stop doing this*, and instead move over to the new method, which was created in response to a few recent requests and concerns. It's also an *important* thing to do, because it ensures that things actually stay up to date. [The below instructions follow from "Standalone Kernel Built-in Module" in the documentation.](https://git.zx2c4.com/android_kernel_wireguard/about/)

First remove what you did before:

```
$ rm -rf path/to/kernel/net/wireguard # or just revert your previous commit
```

Now run the persistent patcher script and commit its results:

```
$ cd /tmp && git clone https://git.zx2c4.com/android_kernel_wireguard/
$ cd android_kernel_wireguard/standalone-kernel
$ ./patch-kernel.sh path/to/kernel
$ cd /tmp && rm -rf android_kernel_wireguard
$ cd path/to/kernel && git add . && git commit -m "net/wireguard: add to tree via updater mechanism"
```

That should be all that's required. This method is quite new, so it's possible there will be some friction, but let me know how it goes, and I'll address bugs quickly if there are any.

**Comment by msdx321** [comment]
Okay sure, going to revert what I did before and using the new method. Thanks for creating this issue.
